name: Release

on:
  release:
    types:
      - published

env:
  REGISTRY_ALIAS: metaphor
  IMAGE_NAME: awslb2cwlogs
  DOCKERFILE_PATH: Dockerfile

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        working-directory: src
        run: npm i

      - name: Run tests
        working-directory: src
        run: npm test

  build:
    runs-on: ubuntu-latest
    needs: test
    permissions:
      contents: read
      id-token: write
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Configure AWS creds
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_ROLE_ARN }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          mask-password: "true"
          registry-type: public

      - name: Build and push arm64 image
        uses: docker/build-push-action@v5
        with:
          platforms: linux/arm64
          file: ${{ env.DOCKERFILE_PATH }}
          push: true
          provenance: false
          tags: >-
            ${{ steps.login-ecr.outputs.registry }}/${{ env.REGISTRY_ALIAS }}/${{ env.IMAGE_NAME }}:arm64-${{ github.sha }},
            ${{ steps.login-ecr.outputs.registry }}/${{ env.REGISTRY_ALIAS }}/${{ env.IMAGE_NAME }}:arm64-${{ github.ref_name }},
            ${{ steps.login-ecr.outputs.registry }}/${{ env.REGISTRY_ALIAS }}/${{ env.IMAGE_NAME }}:arm64-latest
          cache-from: type=gha,scope=arm64-${{ env.IMAGE_NAME }}
          cache-to: ${{ format('type=gha,mode=max,scope=arm64-{0}', env.IMAGE_NAME)}}

      - name: Build and push amd64 image
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64
          file: ${{ env.DOCKERFILE_PATH }}
          push: true
          provenance: false
          tags: >-
            ${{ steps.login-ecr.outputs.registry }}/${{ env.REGISTRY_ALIAS }}/${{ env.IMAGE_NAME }}:amd64-${{ github.sha }},
            ${{ steps.login-ecr.outputs.registry }}/${{ env.REGISTRY_ALIAS }}/${{ env.IMAGE_NAME }}:amd64-${{ github.ref_name }},
            ${{ steps.login-ecr.outputs.registry }}/${{ env.REGISTRY_ALIAS }}/${{ env.IMAGE_NAME }}:amd64-latest
          cache-from: type=gha,scope=amd64-${{ env.IMAGE_NAME }}
          cache-to: ${{ format('type=gha,mode=max,scope=amd64-{0}', env.IMAGE_NAME)}}
